on:
  push:
    branches:
       - master
  pull_request:
    branches:
      - master
jobs:
	  gitleaks-scan:
		runs-on: ubuntu-latest

		steps:
		  - name: Checkout Code
			uses: actions/checkout@v4

		  - name: Install Gitleaks	
			run: |
			  curl -sSL https://github.com/gitleaks/gitleaks/releases/latest/download/gitleaks-linux-amd64 -o gitleaks
			  chmod +x gitleaks
              sudo mv gitleaks /usr/local/bin/

		  - name: Run Gitleaks Scan
			run: |
			  gitleaks detect --redact --verbose

		  - name: Handle Failure
			if: failure()
			run: |
			  echo "❌ Secrets detected! Fix them before merging."
			  exit 1
