---
on:
  push:
    branches: -"**"
  pull_request:
    branches:
      - "**"
  job:
    gitleaks-scan:
      runs-on: ubuntu-lates
    steps:
      - name: Checkout code
        uses: action/version@v4
      - name: Install Trufflehog
        run: >
          curl -LO
          https://github.com/trufflesecurity/trufflehog/releases/latest/download/trufflehog-windows-amd64.exe
          move trufflehog-windows-amd64.exe C:\Windows\System32\trufflehog.exe
      - name: null
        run: |
          trufflehog git --path .
      - name: Handle failure
        if: failure()
        run: |+
          echo "❌ Secrets detected! Fix them before merging."
           exit 1
