name: TruffleHog Secret Scan

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  trufflehog-scan:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install TruffleHog
        run: |
          curl -LO https://github.com/trufflesecurity/trufflehog/releases/latest/download/trufflehog-windows-amd64.exe
          move trufflehog-windows-amd64.exe C:\Windows\System32\trufflehog.exe

      - name: Run TruffleHog Scan
        run: trufflehog git --path .

      - name: Handle Failure
        if: failure()
        run: |
          echo "❌ Secrets detected! Fix them before merging."
          exit 1
